# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
#hello:
#    pattern:  /hello/{name}
#    defaults: { _controller: AcmeDemoBundle:Demo:hello }
AcmeDemoBundle:
  resource: "@AcmeDemoBundle/Resources/config/routing.yml"
  prefix: /